_target_: lightning_rl.player.player.Player
agent_cfg: ${agent}
model_cfg: ${model}
environment_id: ${environment.id}
save_rendering: True
keep_last_n: 5
rendering_path: "./rendering"
_recursive_: False