# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - agent: default.yaml
  - optimizer: default.yaml
  - model: default.yaml
  - hydra: default.yaml
  - environment: default.yaml
  - player: default.yaml
  - tester: default.yaml
  - trainer: default.yaml

work_dir: ${hydra:runtime.cwd}
debug: False
print_config: True
ignore_warnings: True
num_threads: 1
